version: "3.7"
services:
  app:
    build:
      args:
        user: pin-gen
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql/data:/var/lib/

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/

  node:
    image: node
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: "tail -f /dev/null"
